TeamGleason/SpeakFaster

- Observer/SpeakFasterObserver Decoder/process_keypresses.py
- Observer/SpeakFasterObserver/FormMain.cs
Fix #44 - datetime formatting was done in 12hr format rather than 24hr format
Adjust script output to generate json more compatible with visualization tooling.
> Updates to scripts and SPO app

- Observer/SpeakFasterObserver/AudioInput.cs
Fixes #67 
The reason for the empty .flac audio files was the fact that the `flacWriter` object's creation was not in sync with the ingestion
of the actual audio data (via the `WaveDataAvailable()` method). This change moves the creation of the `flacWriter` object into
`WaveDataAvailable()`.
> [Observer] Improve the way files are created to avoid empty .flac files

- Observer/SpeakFasterObserver/AudioInput.cs
- Observer/SpeakFasterObserver/FileNaming.cs
- Observer/SpeakFasterObserver/FormMain.cs
- Observer/SpeakFasterObserver/SpeakFasterObserver.csproj
- Observer/SpeakFasterObserver/Upload.cs
...and change capitalization per standard .net naming conventions.
> Add data hashing w/ salt

- Observer/SpeakFasterObserver Decoder/audio_asr.py
- Observer/SpeakFasterObserver Decoder/audio_asr_test.py
- Observer/SpeakFasterObserver Decoder/elan_format_raw.py
> [Observer Decoder] Accommodate gaps between audio files

- Observer/SpeakFasterObserver Decoder/elan_process_curated.py
- Improves the error message for when curator forgets to change
the auto-generated speaker ID in an utterance
- If a *-SessionEnd.bin file exists, read its proto content and
saves it to the json file.
- Output a processed_speech_only.tsv file, which contains only
the SpeechTranscripts tier, alongside curated_processed.tsv
> [Observer Decoder] Improve error message; read metadata if exists

- Observer/SpeakFasterObserver Decoder/data_manager.py
- Observer/SpeakFasterObserver Decoder/elan_process_curated.py
- Observer/SpeakFasterObserver Decoder/file_naming.py
Session that have completed postprocessing and for which the postprocessing results have been uploaded to remote will be marked by the green font color. See screenshot:
Also in this CL:
- By clicking the "Summarize" button, you can see a kps (keypresses per second) statistic for each session
- Print a message to prompt the end of preprocessing-result uploading
> [Data Manager] Add buttons for postprocessing curation results and uploading postproc data

- webui/README.md
- webui/src/app/app.component.html
- webui/src/app/app.component.spec.ts
- webui/src/app/app.component.ts
- webui/src/app/app.module.ts
- webui/src/app/external/external-events-component.spec.ts
- webui/src/app/external/external-events.component.html
- webui/src/app/external/external-events.component.ts
- webui/src/app/external/external-events.module.ts
- webui/src/app/metrics/metrics.component.html
- webui/src/app/metrics/metrics.component.ts
- webui/src/app/metrics/metrics.module.ts
- webui/src/app/metrics/metrics.spec.ts
- webui/src/app/types/text-entry.ts
- webui/src/utils/cefsharp.ts
- listens for external keypresses in the form of Win32 virtual key
codes.
- displays overall and latest speed (WPM) and keystroke saving rate
(KSR) metrics in real time
- detailed UI design and polishing is deferred to later PRs
See screenshot:
Fixes #125
> Add ExternalEventsComponent & MetricsComponent

- Observer/SpeakFasterObserver Decoder/data_manager.py
- Check for aws on path when starting up
- Fix some wrong variable names
- Remove unused lines
> Data manager: Some minor fixes

- Observer/SpeakFasterObserver Decoder/data_manager.py
> [Data Manager] Fix uploading: upload the .wav and .mp4 files

- Observer/SpeakFasterObserver Decoder/data_manager.py
> [Data manager] Add missing call to _print_time_summary_table()

- Observer/SpeakFasterObserver Decoder/data_manager.py
- Observer/SpeakFasterObserver Decoder/elan_process_curated.py
- Observer/SpeakFasterObserver Decoder/elan_process_curated_test.py
- Allow Speaker:Redacted in Speaker ID
- Data manager: Do not re-list sesssion after postprocessing curation
> [Data Manager] Allow Speaker:Redacted in Speaker ID

- Observer/SpeakFasterObserver Decoder/data_manager.py
- The value "session" is added to the existing value set of
"sessions_changed" ({True, False}), which indicates that only
refresh the state of the selected session, instead of refreshing
the state of all sessions.
> [Data Manager] Better refreshing logic after postprocessing & upload

- Observer/SpeakFasterObserver Decoder/data_manager.py
- Instead, refresh only the state of the affected session
> [Data Manager] Remove more unnecessary listing of all sessions

- Observer/SpeakFasterObserver Decoder/audio_asr.py
> Add more debug info when audio concatenation fails

- Observer/SpeakFasterObserver Decoder/data_manager.py
- Observer/SpeakFasterObserver Decoder/freeform_text.py
- Observer/SpeakFasterObserver Decoder/freeform_text_test.py
- Observer/SpeakFasterObserver Decoder/transcript_lib.py
> [Data Manager] Add button for processing and uploading free-form text

- Observer/SpeakFasterObserver Decoder/audio_asr.py
- Observer/SpeakFasterObserver Decoder/audio_asr_test.py
- If the misaligment between the beginning timestamp of an audio file
and the ending timestamp of the previous audio file is bigger than
0.5 s but less than 2.0 s, we truncate the head of the audio file
to compensate for the timing error.
- Misalignments that are > 2.0 s will lead to errors like before.
Fixes #149
> [Data preprocessing] Truncate audio for misalignments not too big

- Observer/SpeakFasterObserver Decoder/data_manager.py
> [Data Manager] Add buttons: claim session and unclaim session

- webui/src/app/abbreviation/abbreviation.component.spec.ts
- webui/src/app/abbreviation/abbreviation.component.ts
- webui/src/app/app-state-registry.ts
- webui/src/app/app.component.spec.ts
- webui/src/app/app.component.ts
- webui/src/app/context/context.component.spec.ts
- webui/src/app/context/context.component.ts
- webui/src/app/event-logger/event-logger-impl.ts
- webui/src/app/event-logger/event-logger.spec.ts
- webui/src/app/event-logger/event-logger.ts
- webui/src/app/external/external-events.component.ts
- webui/src/app/input-bar/input-bar.component.html
- webui/src/app/quick-phrases/quick-phrases.component.spec.ts
- webui/src/app/quick-phrases/quick-phrases.component.ts
- webui/src/app/settings/settings.component.spec.ts
- webui/src/app/settings/settings.component.ts
- webui/src/utils/keyboard-utils.ts
- The EventLogger logs user events in the app such as starting the app, switching between different tabs of the app, keypresses (without text content), abbreviation expansion triggers, word replacements, spelling for abbreviation expansion, TTS output and keystroke injection, adding, removing and selecting quick phrases, and changing settings, etc.
- Including the EventLogger abstract interface and HTTP based
implementation
- Helper methods are included in events-logger-impl.ts
- Unit tests are added
> [WebUI] Add EventLogger class

- webui/README.md
- webui/src/app/favorite-button/favorite-button.component.spec.ts
- webui/src/app/favorite-button/favorite-button.component.ts
- webui/src/app/input-bar/input-bar.component.html
- webui/src/app/input-bar/input-bar.component.spec.ts
- webui/src/app/input-bar/input-bar.component.ts
- webui/src/app/settings/hostinfo.ts
- webui/src/app/settings/settings.component.html
- webui/src/app/settings/settings.component.spec.ts
- webui/src/app/settings/settings.component.ts
- webui/src/app/settings/version.ts
- webui/src/utils/cefsharp.ts
Also in this PR: bump version from 0.0.3 to 0.0.4.
Fixes https://github.com/TeamGleason/SpeakFaster/issues/268
> [WebUI] Add code to get host app version; Fix lingering text after favorite-phrase add

- webui/src/app/help/help.component.html
- webui/src/app/help/help.component.ts
- webui/src/app/help/help.module.ts
- webui/src/app/quick-phrases/quick-phrases.component.html
- webui/src/app/quick-phrases/quick-phrases.component.spec.ts
- webui/src/app/quick-phrases/quick-phrases.component.ts
- webui/src/app/quick-phrases/quick-phrases.module.ts
- webui/src/app/scroll-buttons/scroll-button.component.spec.ts
- webui/src/app/scroll-buttons/scroll-button.component.ts
- webui/src/app/scroll-buttons/scroll-buttons.component.html
- webui/src/app/scroll-buttons/scroll-buttons.modue.ts
- Refactor the gaze-clickable scroll buttons into its own Angular
component: ScrollButtonsComponent
- Use the new ScrollButtonsComponent in both QuickPhrasesComponent
and HelpComponent
Fixes https://github.com/TeamGleason/SpeakFaster/issues/275
> [WebUI] Add gaze scroll buttons to help page

- webui/src/app/settings/settings.component.html
- webui/src/app/settings/version.ts
> [WebUI] Add speaking rate options 1.1 and 1.2; Bump version to 0.0.5

- webui/src/app/app.component.html
- webui/src/app/app.component.ts
- webui/src/app/app.module.ts
- webui/src/app/context/context.component.ts
- webui/src/app/context/remote-control.ts
- webui/src/app/event-logger/event-logger-impl.ts
- webui/src/app/event-logger/event-logger.spec.ts
- webui/src/app/event-logger/event-logger.ts
- webui/src/app/scroll-buttons/scroll-button.component.ts
- webui/src/app/settings/settings.component.html
- webui/src/app/settings/settings.component.spec.ts
- webui/src/app/settings/settings.component.ts
- webui/src/app/settings/settings.spec.ts
- webui/src/app/settings/settings.ts
- webui/src/app/text-to-speech/text-to-speech.component.ts
- webui/src/app/tts-voice-selection/tts-voice-selection.component.html
- webui/src/app/tts-voice-selection/tts-voice-selection.component.ts
- webui/src/app/tts-voice-selection/tts-voice-selection.module.ts
- webui/src/app/tts-voice-selection/tts-voice-selection.spec.ts
- webui/src/app/types/app-state.ts
- Turn on by the remote-control command "Study on"
- Add `TtsVoiceSelectionComponent` to let the user select a voice from the voices returned by `speechSynthesis.getVoices()`.
Fixes https://github.com/TeamGleason/SpeakFaster/issues/295
> [WebUI] Add full-logging mode and TTS voice selection component

- webui/src/app/input-bar/input-bar.component.spec.ts
- webui/src/app/input-bar/input-bar.component.ts
> [WebUI] Remove trailing spaces before added punctuation in injected text

- webui/src/app/input-bar/input-bar.component.spec.ts
- webui/src/app/input-bar/input-bar.component.ts
> [WebUI] Update button boxes after repeated appendText events

- webui/README.md
- webui/src/app/app.component.spec.ts
- webui/src/app/app.component.ts
- webui/src/app/context/context.component.ts
- webui/src/utils/cefsharp.ts
> [WebUI] Hook for device status

- webui/src/app/app.component.html
- webui/src/app/context/context.component.html
- webui/src/app/context/context.component.spec.ts
- webui/src/app/context/context.component.ts
- webui/src/app/conversation-turn/conversation-turn.component.html
- webui/src/app/conversation-turn/conversation-turn.component.spec.ts
- webui/src/app/conversation-turn/conversation-turn.component.ts
to prevent slight cut off at the bottom of the UI.
> [WebUI] Reduce context height under study mode

- webui/src/app/help/help.component.html
related to the simplification surrounding contractions.
> [WebUI] Update instructions for abbreviation in help page

- webui/src/app/abbreviation-refinement/abbreviation-refinement.component.html
- webui/src/app/input-bar/input-bar.component.ts
* separate them farther from the context phrases
* also fix a bug related to the speaker button under AE auto fire
> [WebUI] Move the replacement word options down in layout

- webui/src/app/study/study-manager.ts
> [WebUI] Add dummy dialog #3

- webui/src/app/speakfaster-service.ts
Also add the support for `runAsMe`.
> [WebUI] Fix SpeakFasterService.ping()

- data_analysis/wer_anova.py
> Add user study analysis Python scripts:

- webui/README.md
- webui/package-lock.json
- Update node version
- Add info about the `--openssl-legacy-provider` flag
> Updating webui/README.md
