TeamGleason/SpeakFaster

Observer/SpeakFasterObserver/AudioInput.cs, Observer/SpeakFasterObserver/FileNaming.cs, Observer/SpeakFasterObserver/FormMain.Designer.cs, Observer/SpeakFasterObserver/FormMain.cs, Observer/SpeakFasterObserver/Properties/Settings.Designer.cs, Observer/SpeakFasterObserver/Properties/Settings.settings, Observer/SpeakFasterObserver/SpeakFasterObserver.csproj, Observer/SpeakFasterObserver/Upload.cs
File format:
- The audio files are named in the pattern of `20210629T132215079-MicWaveIn.flac`, which is consistent with the keypresses protobuf files and the screenshot jpg files.
- The audio is sampled at 16000 Hz mono (single channel). 
- To save space, the [FLAC encoding](https://xiph.org/flac/) is used. The FLAC format is supported by services such as [Google Cloud speech-to-text](https://cloud.google.com/speech-to-text/docs/encoding)
- Each .flac file is approximately 1-minute long.
Other info:
- The added audio recording feature follows the existing on/off control based on system-tray icon clicks.
Added dependencies:
- NAudio for reading audio input from microphone
- FlacBox for FLAC encoding
=> Observer: Record audio from microphone

Observer/SpeakFasterObserver Decoder/README.md, Observer/SpeakFasterObserver Decoder/audio_asr.py, Observer/SpeakFasterObserver Decoder/audio_asr_test.py, Observer/SpeakFasterObserver Decoder/file_naming.py, Observer/SpeakFasterObserver Decoder/file_naming_test.py, Observer/SpeakFasterObserver Decoder/requirements.txt
by using Google Cloud Speech-to-Text service.
- it works with a series of .wav or .flac files
- it performs streaming recognition to avoid unnecessary file
uploading
- the results are written to a .tsv file with a format like in the
the following example:
```
tBegin  tEnd    Tier    Content
11.830  12.830  SpeechTranscript        would you like to sit down
15.500  16.500  SpeechTranscript        no I'm fine standing up
19.170  20.170  SpeechTranscript        are you sure you don't want to sit down
```
- add supporting module file_naming to parse data file names, including
timestamp and data stream name.
- add unit tests
Pair programming with @vsubhashini 
This PR is related to the offline analysis for #59 and #60
=> [Decoder] Add script for transcribing speech in audio

Observer/SpeakFasterObserver Decoder/README.md, Observer/SpeakFasterObserver Decoder/audio_asr.py, Observer/SpeakFasterObserver Decoder/audio_asr_test.py
The .tsv output file with diarization has a format that looks like the following example:
```tsv
tBegin	tEnd	Tier	Content
377.974	380.374	SpeechTranscript	it feels good to stretch my legs a bit (Speaker #1)
382.974	384.474	SpeechTranscript	would you like to go to the mall (Speaker #2)
```
The script is revised in order to support infinite (endless) streaming recognition.
This is achieved by breaking the audio file paths into groups < 4 minutes (240 seconds) and creating
separate generators for them.
Fixes #72
Fixes #73
=> audio_asr.py: Support diarization and infinite streaming

Observer/SpeakFasterObserver/AudioAsr.cs, Observer/SpeakFasterObserver/AudioInput.cs, Observer/SpeakFasterObserver/SpeakFasterObserver.csproj, Observer/SpeakFasterObserver/SpeechAnalyzer.cs
based on the Google Cloud Speech-to-text API.
The new module `AudioAsr` is disabled through a boolean by default. It can be enabled by setting the boolean flag to true
and setting the proper Google Cloud credentials (see doc strings in `AudioInput.cs` for details.
The `AudioAsr` modules supports ASR (transcript only) and diarization (tagging different speakers).
=> [Observer] Add code for online ASR & diarization

Observer/SpeakFasterObserver Decoder/audio_asr.py, Observer/SpeakFasterObserver Decoder/elan_format_raw.py, Observer/SpeakFasterObserver Decoder/object_detection_test.py
- Use square brackets `[]` instead of parentheses `()` for speaker labels for consistency with the proposed
data curation process.
- Avoid hardcoding GCloud Speech-to-text async timeout. Instead, calculate the timeout based on the audio duration
- Better error message for reading audio files
- Fix a broken test in object_detection_test.py
Towards #60
=> [Observer Decoder] Minor improvements

Observer/SpeakFasterObserver/AudioAsr.cs, Observer/SpeakFasterObserver/Properties/Settings.Designer.cs, Observer/SpeakFasterObserver/Properties/Settings.settings, Observer/SpeakFasterObserver/SpeakFasterObserver.csproj
in conjunction with Google Cloud ASR and diarization to recognize known speakers.
The code assumes that speakers have been enrolled and that their profile IDs are stored in a .json file
pointed to by the `SPEAK_FASTER_SPEAKER_ID_CONFIG` environment variable.
The .json file should additionally contain the Azure speech subscription key and the Azure endpoint.
We are parking the code in Observer for now. But the code should be moved to Talk37 for context
extraction in the future.
=> [Observer] Demonstrate how to use Azure Speaker ID in real time

Observer/SpeakFasterObserver Decoder/audio_asr.py, Observer/SpeakFasterObserver Decoder/elan_format_raw.py, Observer/SpeakFasterObserver Decoder/file_naming.py, Observer/SpeakFasterObserver Decoder/file_naming_test.py, Observer/SpeakFasterObserver Decoder/video.py
This change makes the date parsing functions work with UTC timestamps
such as 20211015T183436163Z.
Related to #76
=> [Observer Decoder] Accommodate UTC timestamps

Observer/SpeakFasterObserver/AudioInput.cs, Observer/SpeakFasterObserver/FileNaming.cs, Observer/SpeakFasterObserver/FormMain.cs, Observer/SpeakFasterObserver/SessionManager.cs, Observer/SpeakFasterObserver/Upload.cs
Motivation: 
- Divide the data into manageable chunks that are the sessions
General idea:
- As proposed in the discussion thread of #79, use the user event of focusing on the text editor as the candidates for the implicit session boundaries. 
- To accommodate the previous context before the focus onto the text editor, we use a rolling buffer and a leading time window of 5 minutes. Any recordings that happen within 5 minutes of the focusing event will be included in the session. 
- Created the new class SessionManager.cs to house the logic.
- The session subdirectories have the naming convention `session-${timestamp_in_utc}`, e.g., `"session-20211014T190724113Z"`.
Also in this change:
- Add an explicit session end token named `${timestamp}-SessionEnd.bin` in the session subdir when a …
=> [Observer] Save data files into session subdirectories

Observer/SpeakFasterObserver Decoder/requirements.txt
This avoids a version skew issues observed during debugging with @seanholmes77
=> [Observer Decoder] Pin tensorflow-estimator version to 2.6.0

Observer/SpeakFasterObserver/Properties/Settings.Designer.cs, Observer/SpeakFasterObserver/Upload.cs
Empirically, we've observed this exception being thrown and not caught properly when Wifi goes out in the middle of an Observer session.
=> [Observer] Catch System.Net.Http.HttpRequestException during S3 PUT

Observer/SpeakFasterObserver Decoder/audio_asr.py, Observer/SpeakFasterObserver Decoder/data_manager.py, Observer/SpeakFasterObserver Decoder/elan_format_raw.py, Observer/SpeakFasterObserver Decoder/elan_process_curated.py, Observer/SpeakFasterObserver Decoder/file_naming.py
- Support showing the objects under a session prefix in the S3 bucket
- Support downloading the objects under a session prefix to a local folder, via subprocess call of `aws s3 sync ...`
- Support running preprocessing of a downloaded session folder, via subprocess call of `python elan_format_raw.py`
- Support uploading preprocessing results to the corresponding S3 bucket
- Display remote and local status in the session list
- 
See screenshot based on a test S3 bucket:
=> [Observer Decoder] Support downloading, preproc & uploading in data_manager.py

Observer/SpeakFasterObserver Decoder/data_manager.py
Bug fixes:
- Previously, the list_object_v2() call didn't do pagination, so it
only returned the first 1000 objects. As a result, the UI incorrectly
showed sessions with more than 1000 objects as "not complete". This
is now fixed through pagination.
Improvements:
- Decreased the width and height of the window to make it easier to
work with on screens with relatively low resolution.
- Highlight sessions that have the "PREPROCESSED" remote status
with the blue color.
- For sessions that ended prematurely and hence lack the SessionEnd.bin
object, pop up a PySimpleGUI text box to ask for the time zone.
- Display the total count of objects for a session
- Remove the "Show session" button. Let selection events in the session
list automatically display session details.
Fixes #118
=> [Data Manager GUI] Improvements and bug fixes

Observer/SpeakFasterObserver Decoder/data_manager.py
Session list is sped up through more efficient `list_objects_v2()` calls. 
On my laptop, listing 114 sessions previously took about 8 seconds. With this change it takes about 3-4 seconds (50%+ speed up)
Example summary table for time-of-day and day-of-week
```
=== Distribution of session start times ===
0-3	3-6	6-9	9-12	12-15	15-18	18-21	21-24
Mon	0	0	0	0	0	2	2	12
Tue	0	0	0	7	15	10	7	6
Wed	0	0	0	17	5	3	6	1
Thu	0	0	1	3	1	1	4	5
Fri	0	0	0	2	1	0	0	0
Sat	0	0	0	2	0	0	0	1
Sun	0	0	0	0	0	0	0	0
```
=> [Data Manager] Speed up session listing; add time summary table

Observer/SpeakFasterObserver Decoder/data_manager.py
Related to #128
New summary table contains a sum over the days of the week and over the hour ranges, e.g.,
```
=== Distribution of session start times ===
0-3	3-6	6-9	9-12	12-15	15-18	18-21	21-24
Mon	0	0	0	0	0	2	2	12	16
Tue	0	0	0	7	15	10	7	6	45
Wed	0	0	0	17	5	3	6	1	32
Thu	0	0	1	3	1	1	4	5	15
Fri	0	0	0	2	1	0	0	0	3
Sat	0	0	0	2	0	0	0	1	3
Sun	0	0	0	0	0	0	0	0	0
-------------------------------------------
0	0	1	31	22	16	19	25
```
=> [SpeakFaster] Print day and hour range summaries in the time table

Observer/SpeakFasterObserver Decoder/data_manager.py
- Speed up listing of sessions by using `paginator.search()`. Measurement on my workstation: 3.x s --> 2.x s. (~30% speed up)
- Add "Refresh session state" button to allow refreshing the state of a single session in the session list without going through all sessions
- Keep scroll state when updating session lists
- Add button "Preprocess and upload sessions from here on" to support batch downloading, preprocessing and uploading of sessions.
Fixes #137
=> [Data manager] Speed up + "Refresh session state" and "Batch preproc" buttons

Observer/SpeakFasterObserver Decoder/data_manager.py, Observer/SpeakFasterObserver Decoder/data_manager_test.py, Observer/SpeakFasterObserver Decoder/gcloud_utils.py
This button allows the user to upload a postprocessed session to the designated GCS bucket.
- When the "Upload to GCS" button is clicked, a dialog box first pops up asking the user to confirm that they intend to upload the data o the GCS bucket.
- Then it checks whether the files (curated_processed.tsv, curated_processed.json and curated_processed_speech_only.tsv) already exist in the GCS bucket and if so, pops up a dialog so the user can confirm overwriting the files.
- If the user confirms to upload and overwrite the files, the actual object uploading ensues
- After the user clicks the "Summarize" button, the session list will display the "[GCS: UPLOADED]" vs "[GCS: NOT_UPLOADED]" strings for the sessions of which the remote state is "POSTPROCESSED". The ones that have been uploaded to …
=> [Data Manager] Add "Upload to GCS" button

webui/src/app/abbreviation/abbreviation.component.ts, webui/src/app/app.component.html, webui/src/app/app.module.ts, webui/src/app/text-to-speech-service.ts, webui/src/app/text-to-speech/text-to-speech.component.html, webui/src/app/text-to-speech/text-to-speech.component.spec.ts, webui/src/app/text-to-speech/text-to-speech.component.ts, webui/src/app/text-to-speech/text-to-speech.module.ts, webui/src/app/types/text-entry.ts, webui/src/app/types/text-to-speech.ts
- Implements the "speak" button
- Clicking the button triggers a call to the /tts route to retrieve the
audio waveform
- This supports custom voices and flexible volume control
- The base64-encoded audio waveform is then attached to the src
attribute of a hidden HTML audio element to enable audio playback
- Error messages are displayed on the top-right corner of the UI
when error occur
=> [WebUI] Add TextToSpeechComponent

Observer/SpeakFasterObserver Decoder/elan_process_curated.py, Observer/SpeakFasterObserver Decoder/elan_process_curated_test.py
This label is a newly added label to indicate that an annotation in the SpeechTranscripts tier is unrelated background speech and hence not subject to ASR error correction or timing correction.
=> [Observer Decoder] Add logic for [BackgroundSpeech] label

webui/src/app/abbreviation/abbreviation.component.html, webui/src/app/abbreviation/abbreviation.component.spec.ts, webui/src/app/abbreviation/abbreviation.component.ts, webui/src/app/abbreviation/abbreviation.module.ts, webui/src/app/app.component.html, webui/src/app/context/context.component.ts, webui/src/app/external/external-events-component.spec.ts, webui/src/app/external/external-events.component.ts, webui/src/app/spell/spell.component.html, webui/src/app/spell/spell.component.spec.ts, webui/src/app/spell/spell.component.ts, webui/src/app/spell/spell.module.ts, webui/src/app/types/abbreviation.ts, webui/src/utils/text-utils.spec.ts, webui/src/utils/text-utils.ts
Towards fixing #49 
When initial abbreviation expansion fails:
Let's suppose you want to say "I feel a little groggy", but the option isn't provided (even though it is actually available in the example in the screenshot above!) You can click the letter that corresponds to the "g" or simply type "g" with the keyboard.
The screenshot above shows when you have typed out the word "groggy". Then you can type Space or Enter to trigger AE again, this time with keyword.
This will narrow down the AE options and bring up the desired phrase, as shown in the example above.
Additional facts about the `SpellComponent`'s recovery-from-AE-failure feature (not shown in the above screenshots):
- More than one words can be spelled out
- When there are duplicate letters in an abbreviation (e.g., "i feel …
=> [WebUI] Refactor keyboard listening logic; Add keyword-based AE

webui/src/app/auth/auth.component.spec.ts, webui/src/app/auth/auth.component.ts
Fixes #164
This allows the host app, which *can* persist refresh tokens, to
pass the access token directly into the WebUI. This gets rid of the
need to do limited-input OAuth. 
The host C# app performs the usual OAuth workflow as shown in the example:
https://github.com/googlesamples/oauth-apps-for-windows
and stores the refresh token, which can be used to acquire new access tokens
in the future (after app or system restart).
=> [WebUI] Accept access_token route parameter

webui/src/app/abbreviation/abbreviation.component.html, webui/src/app/abbreviation/abbreviation.component.spec.ts, webui/src/app/abbreviation/abbreviation.component.ts, webui/src/app/abbreviation/abbreviation.module.ts, webui/src/app/app.component.html, webui/src/app/conversation-turn/conversation-turn.component.html, webui/src/app/conversation-turn/conversation-turn.component.ts, webui/src/app/phrase/phrase.component.html, webui/src/app/phrase/phrase.component.ts
- Prevents the spell buttons from becoming not gaze-clickable during the spelling
- Make the options available even during spelling in case the users changes the mind and would like to give up spelling and just choose on of the existing options
- Add mat-spinner during server calls
- Prevent long `ContextTurnComponents` at the top from changing the position of AE options down below.
- Prevent text overflow in `PhraseComponent`s in `AbbreviationComponet`; prevent button cutoff
- ![image](https://user-images.githubusercontent.com/16824702/152215349-5cec3133-d1f6-4660-af34-bc33bf207235.png)
- When no AE option is available: provide message and "try again" button:
- ![image](https://user-images.githubusercontent.com/16824702/152198923-ab74c58f-1255-406d-b1ef-5de67147ff29.png)
Fixes #157 …
=> [WebUI] A few improvements and fixes for AbbreviationComponent

webui/src/app/abbreviation/abbreviation.component.html, webui/src/app/abbreviation/abbreviation.component.spec.ts, webui/src/app/abbreviation/abbreviation.component.ts, webui/src/app/context/context.component.ts, webui/src/app/external/external-events-component.spec.ts, webui/src/app/external/external-events.component.ts, webui/src/app/metrics/metrics.component.ts, webui/src/app/metrics/metrics.spec.ts, webui/src/app/spell/spell.component.ts, webui/src/app/types/text-entry.ts
Fixes #172
Fixes #177 
- Move the "Expand abbreviation" button away from the edge. Make it big and easier to gaze-click:
- ![image](https://user-images.githubusercontent.com/16824702/152386378-871a3e10-d10e-4960-acbe-9c6137a23572.png)
- Add "Abort" (X) button at the end of the available options
- ![image](https://user-images.githubusercontent.com/16824702/152386846-bfb580e2-1fef-4b81-a6e9-59a0c9a657f8.png)
- Clean ups:
- In `AbbreviationComponent`, remove the private member `requestOngoing` and fold the state logic into `state` (new enum value: `REQUEST_ONGOING`)
=> [WebUI] Add expand and abort buttons for abbreviaton expansion

webui/src/app/abbreviation/abbreviation.component.spec.ts, webui/src/app/app.component.html, webui/src/app/app.component.spec.ts, webui/src/app/app.component.ts, webui/src/app/quick-phrases/quick-phrases.component.html, webui/src/app/quick-phrases/quick-phrases.component.spec.ts, webui/src/app/quick-phrases/quick-phrases.component.ts, webui/src/app/quick-phrases/quick-phrases.module.ts, webui/src/app/speakfaster-service.ts, webui/src/app/types/contextual_phrase.ts
- Create new type definitions in `contextual_phrase.ts`. These are related to the contextual phrases (aka quick phrases) and their associated contexts.
- Refactor the existing interface method `SpeakFasterService.textPrediction()` to accommodate contextual phrase retrieval from backend.
- Remove the hardcoded phrases in `app.componnet.ts`. Replace them with the `allowsTags` argument values that are used by different tabs of quick phrases.
- Refactor `QuickPhrasesCompnent` to adapt to these chagne; update related unit tests.
- In `QuickPhrasesComponent`, add UI elements to show the request-pending and error states.
=> [WebUI] Call service to get quick phrases; remove hardcoding

webui/README.md, webui/src/app/app.component.html, webui/src/app/app.component.ts, webui/src/app/app.module.ts, webui/src/app/conversation-turn/conversation-turn.component.ts, webui/src/app/input-bar/input-bar.component.html, webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/input-bar/input-bar.module.ts, webui/src/app/quick-phrases/quick-phrases.component.html, webui/src/app/spell/spell.component.html, webui/src/app/spell/spell.component.spec.ts, webui/src/app/spell/spell.component.ts, webui/src/app/types/abbreviation.ts, webui/src/utils/datetime-utils.spec.ts, webui/src/utils/datetime-utils.ts
- See screenshot of the newly-added `InputBarComponent`, where the 2nd (favorite) button is not yet functional.
- ![image](https://user-images.githubusercontent.com/16824702/153298235-a9e458fa-c5f2-4161-bb09-9f62dae48ca9.png)
- Fixes #184: Remove timestamp from `ConversationTurnComponent` by default
- Fixes #188: Make input elements in `SpellComponent` not focusable in order to prevent double processing of keypresses
- Hide `MetricsComponent` under URL parameter `showMetrics`
=> [WebUI] Add InputBarComponent; Fix a few issues

webui/src/app/text-to-speech-service.ts, webui/src/app/text-to-speech/text-to-speech.component.html, webui/src/app/text-to-speech/text-to-speech.component.spec.ts, webui/src/app/text-to-speech/text-to-speech.component.ts
- Support both cloud TTS (ttsVoiceType === 'PERSONALIZED') and generic local TTS (ttsVoiceType === 'GENERIC')
- In TextToSpeechComponent, remove the constituent UI elements for status display (e.g., playing, error). Instead, delegate the status display to listeners.
Fixes #198
=> [WebUI] Refactor TextToSpeechComponent to support local TTS

Observer/SpeakFasterObserver Decoder/elan_process_curated.py, Observer/SpeakFasterObserver Decoder/elan_process_curated_test.py
Fixes #213 
Previously the `[Unintelligible:(Articulation|Crosstalk|Noise)]` tag was not recognized properly.
=> [Data Manager] Support Unintetlligible label at beginning of transcript

webui/README.md, webui/src/app/abbreviation/abbreviation.component.spec.ts, webui/src/app/abbreviation/abbreviation.component.ts, webui/src/app/external/external-events-component.spec.ts, webui/src/app/external/external-events.component.ts, webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/quick-phrases/quick-phrases.component.spec.ts, webui/src/app/quick-phrases/quick-phrases.component.ts, webui/src/app/test-utils/test-cefsharp-listener.ts, webui/src/utils/cefsharp.ts
This PR includes two loosely-related changes:
1. When injecting text, not only issue keypresses, but also send
the text string as an argument, so that the host can optionally
add it to the system clipboard to support text pasting into other
apps.
Towards: https://github.com/TeamGleason/SpeakFaster/issues/239
2. Handle the shift key properly in the `InputBarComponent`, so that
the letter casing can be reflected in the typed text. Previously
all entered text showed up as lowercase regardless of shift-key
states.
=> [WebUI] Inject string in addition to keypresses; Handle shift keys

Observer/SpeakFasterObserver Decoder/elan_process_curated.py, Observer/SpeakFasterObserver Decoder/elan_process_curated_test.py
Turns out that ELAN sometimes messes up the tEnd values. Since
tEnd values for the keypresses are just dummies (hardcoded to
tBegin + 0.1 s currently), it is fine to ignore them.
=> [Data Manager] Relax tEnd check in check_keypresses()

Observer/SpeakFasterObserver Decoder/video.py, Observer/SpeakFasterObserver Decoder/video_test.py
Always use forward slash during video stitching based on ffmpeg.
=> [Data Manager] Video ffmpeg path issue on Windows

webui/src/app/abbreviation/abbreviation.component.html, webui/src/app/phrase/phrase.component.spec.ts, webui/src/app/phrase/phrase.component.ts, webui/src/app/quick-phrases/quick-phrases.component.spec.ts, webui/src/app/quick-phrases/quick-phrases.component.ts, webui/src/app/speakfaster-service.ts, webui/src/app/types/abbreviation.ts, webui/src/app/types/contextual_phrase.ts
Sorting is by tier:
1. By descending order of last used timestamp
2. In case of tie, sort by creation timestamp
3. In case of tie, sort lexicographically
Fixes https://github.com/TeamGleason/SpeakFaster/issues/241
=> [WebUI] Sort quick phrases by last usage timestamp

webui/README.md, webui/src/app/app.component.spec.ts, webui/src/app/app.component.ts, webui/src/app/external/external-events-component.spec.ts, webui/src/app/external/external-events.component.ts, webui/src/app/settings/settings.component.spec.ts, webui/src/app/settings/settings.component.ts, webui/src/app/settings/settings.spec.ts, webui/src/app/settings/version.ts, webui/src/utils/cefsharp.ts
* Fix incorrect boolean flag in keypress hook call, use Ctrl+W
* Add cefsharp interface methods:
- `bringWindowToForeground()`
- `bringFocusAppToForeground()`
* Remove all registered gaze buttons before page reload.
These subserve toggling between the app and a focus app with a combo key
such as Ctrl + G.
Fixes #280
=> Fix ghost buttons, boolean flag in keypress hook call, use Ctrl+W

webui/src/app/external/external-events-component.spec.ts, webui/src/app/external/external-events.component.ts, webui/src/app/input-bar/input-bar.component.html, webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts
Click events in the `InputBarComponent`'s input-text div previous didn't get handled. In this PR, the events are now handled and are used to place the cursor in the corresponding location.
This PR also fixes the logical for word-backspace (Ctrl+Backspace or Ctrl,Shift,Left,Backspace) for non-final cursor locations.
When cursor is not at the final location, it can insert text into the text in the input bar.
See screenshot:
Known issues: When there is line wrapping in input-text, placing the cursor changes the wrapping, because a line break is inserted right after the cursor.
=> [WebUI] Support basic cursor navigation in InputBarComponent

webui/src/app/external/external-events-component.spec.ts, webui/src/app/favorite-button/favorite-button.component.spec.ts, webui/src/app/favorite-button/favorite-button.component.ts, webui/src/app/input-bar/input-bar.component.html, webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/text-to-speech/text-to-speech.component.ts
Previously, the "repeat last non-empty" feature worked only for the Speak button. This PR makes it work for the Inject and Add-to-favorite buttons as well.
Fixes #307
=> [WebUI] Make favorite button remember last spoken phrase

webui/README.md, webui/src/app/app.component.html, webui/src/app/app.component.spec.ts, webui/src/app/app.component.ts, webui/src/app/external/external-events-component.spec.ts, webui/src/app/external/external-events.component.ts, webui/src/app/help/help.component.html, webui/src/app/help/help.component.spec.ts, webui/src/app/input-bar/input-bar.component.html, webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/keyboard/keyboard.component.ts, webui/src/utils/cefsharp.ts
- When gaze buttons are paused, show status message under the input bar
- Update README.md to document the new cefsharp interface method: `toggleGazeButtonsState()`
- Add info about the `Ctrl + p` toggle combo key to the help component
Fixes #309.
=> [WebUI] Support toggling eye gaze button state

webui/src/app/context/context.component.ts, webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/study/study-manager.spec.ts, webui/src/app/study/study-manager.ts
- From the companion app, to start an unscripted dialog with an initial question, send e.g., `start abbrev u1`.
- Ensures that the displayed text is what's actually selected in the input box or via AE:
- Fixes the issue of attending to earlier commands after a command is handled. This bug happened when there were multiple commands in the context history window.
Fixes #323
=> [WebUI] Support unscripted dialogs for study

webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts
a regression after the recent major refactoring.
Also in this PR: Increase multiplier for the width of the `base-text-area` in `InputBarComponent`.
Fixes #327
=> [WebUI] Fix bug in which inputStringChanged is not called

webui/src/app/abbreviation/abbreviation.component.ts, webui/src/app/context/context.component.spec.ts, webui/src/app/context/context.component.ts, webui/src/app/input-bar/input-bar.component.html, webui/src/app/input-bar/input-bar.component.spec.ts
1. Disable the cut-button for word chips (the "scissor button") when
study is on.
2. Fixes #320. Support up to five context turns during study, even though only the latest three are displayed.
=> [WebUI] Study improvements

webui/src/app/abbreviation/abbreviation.component.html, webui/src/app/abbreviation/abbreviation.component.spec.ts, webui/src/app/app.component.html, webui/src/app/app.component.spec.ts, webui/src/app/app.component.ts, webui/src/app/conversation-turn/conversation-turn.component.html, webui/src/app/input-bar/input-bar.component.html, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/study/study-manager.spec.ts, webui/src/app/study/study-manager.ts
- Under study mode, enable zoom out, so the app UI works in landscape
mode on a mobile device, without being partially obscured by the
onscreen keyboard.
- Disable text predictions and quick phrases during study mode in `AbbreviationComponent`
- Change font in the input bar to avoid confusion such as "I" vs. "l"
- Stay in study mode after dialog ends.
=> [WebUI] Further improvements for study mode

webui/src/app/abbreviation/abbreviation.component.ts, webui/src/app/app.component.html, webui/src/app/app.component.spec.ts, webui/src/app/app.component.ts, webui/src/app/external/external-events-component.spec.ts, webui/src/app/external/external-events.component.ts, webui/src/app/input-bar/input-bar.component.html, webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/study/study-manager.spec.ts, webui/src/app/study/study-manager.ts
- Correctly enforce ignore sequence (e.g., comma followed immediately by a space) in the new textarea in `InputBarComponent`
- During study mode `full`, hide the `Expand` button
- During study mode `abbrev`, hide the `Speak` button, unless under special states including `CHOOSING_WORD_CHIP`, `FOCUSED_ON_WORD_CHIP` and `FOCUSED_ON_LETTER_CHIP` for numChips = 1. Fixes #333.
- Fix the behavior of clicking the Speak button when spelling words: Fixes #334 
- If there is only a single word and it is spelled out to be non-empty, speak the word out loud
- If there are multiple words, and the user is either choosing a letter chip or focused on a letter chip, it is a no-op.
- Adjust the color of the "Expand" button to blue, to make it more salient.
- Fix #336: save input textarea text when adding …
=> [WebUI] Fix key-sequence ignoring, spell-mode speak button click, etc.

webui/src/app/event-logger/event-logger-impl.ts, webui/src/app/event-logger/event-logger.spec.ts
- The logging error occurred when there was the single quote or apostrophe (`'`) character in the text. The error occurred because the character was not properly URL-encoded. This PR adds the encoding. 
- For extra safety, this PR adds retry logic to event logging impl.
Fixes #339 .
=> [WebUI] Fix text logging during study

webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts
`sampleTime()` preserves the last event before a period of silence, whereas debounceTime() does not.
=> [WebUI] Keyword expansion: use sampleTime() instead of debounceTime()

webui/src/app/abbreviation/abbreviation.component.html, webui/src/app/abbreviation/abbreviation.component.spec.ts, webui/src/app/abbreviation/abbreviation.component.ts, webui/src/app/app.component.html, webui/src/app/app.component.ts, webui/src/app/app.module.ts, webui/src/app/auth/auth.component.ts, webui/src/app/event-logger/event-logger-impl.ts, webui/src/app/event-logger/event-logger.ts, webui/src/app/input-bar/input-bar.component.html, webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/input-bar/input-bar.module.ts, webui/src/app/input-text-predictions/input-text-predictions.component.html, webui/src/app/input-text-predictions/input-text-predictions.component.spec.ts, webui/src/app/input-text-predictions/input-text-predictions.component.ts, webui/src/app/input-text-predictions/input-text-predictions.module.ts, webui/src/app/settings/version.ts, webui/src/utils/cefsharp.ts, webui/src/utils/text-utils.spec.ts, webui/src/utils/text-utils.ts
- Display word suggestions (including word completion and next-word prediction) underneath the main input bar.
- The word suggestions are fetched via HTTP GET requests from the `textPrediction()` interface method.
- Both word completion and next-word predictions are covered.
- When the InputTextPredictionsComponent is shown, the `Expand`, `Spell` and `X` buttons are moved to the said component. 
- Add event logging (new event name: `TextPredictionSelection`.
- Add logic to modify the text in the main text in ways dependent on whether the suggestions are for word completion or NWP.
=> [WebUI] Support word suggestions

webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/input-text-predictions/input-text-predictions.component.spec.ts, webui/src/app/input-text-predictions/input-text-predictions.component.ts
Previously, when the input to the word prediction model is something like 'hi,' and the word suggestion 'there' is selected, the resultant input string was 'hi,there', i.e., without a space between 'hi',' and 'there'.
This PR fixes this issue.
=> [WebUI] Fix bug related to word suggestion w/ input ending punctuation

webui/src/app/input-text-predictions/input-text-predictions.component.spec.ts, webui/src/app/input-text-predictions/input-text-predictions.component.ts, webui/src/app/settings/version.ts, webui/src/utils/cefsharp.ts
Expand the number[][] argument to updateButtonBoxes() in the cefsharp
interface, so that if the length of a number[] array is 5, it will be
interpreted as [left, top, right, bottom] followed by the custom
threshold duration in milliseconds (e.g., 400 ms).
Also bumps version from 0.0.9 to 0.0.10.
=> [WebUI] Support gaze buttons with long threshold duration

webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/input-text-predictions/input-text-predictions.component.spec.ts, webui/src/app/input-text-predictions/input-text-predictions.component.ts
Also ensures that the input bar auto-scrolls to the bottom when word predictions are appended.
Fixes #349
=> [WebUI] Prevent word suggestions from showing up when input is empty

webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/settings/settings.component.ts, webui/src/app/speakfaster-service.ts, webui/src/app/types/abbreviation.ts
- The incopmlete keyword AE mode currently is disabled by default. It is enabled only when the user goes to Settings > AI Settings and enables the model explicitly
- Once enabled, in Spelling mode of the input bar, each keypress triggers an AE call (with throttling)
=> [WebUI] Support inckw AE

webui/src/app/app.component.html, webui/src/app/app.component.spec.ts, webui/src/app/app.component.ts, webui/src/app/auth/auth.component.spec.ts, webui/src/app/auth/auth.component.ts, webui/src/app/auth/oauth2-helper.ts, webui/src/app/input-bar-chip/input-bar-chip.component.html, webui/src/app/partner/partner.component.ts, webui/src/app/speakfaster-service.ts, webui/src/app/types/speakfaster-service.spec.ts
- Accommodate new API endpoint format
- Support getting access token from OAuth2 (non limited input device) 
- When access token is available, do not use cookie-based credentials (`withCredentaisl`)
=> [WebUI] Update authentication in a backward compatible way

webui/src/app/text-to-speech/text-to-speech.component.spec.ts, webui/src/app/text-to-speech/text-to-speech.component.ts
TTS, i.e., `window.speechSynthesis`, may be unavailable for certain browsers (e.g., Opera on Android), . If that is the case, we fallback to personalized (cloud) TTS voice automatically.
=> [WebUI] Make TTS selection logic work for browsers without TTS

webui/src/app/abbreviation-refinement/abbreviation-refinement.component.ts, webui/src/app/abbreviation/abbreviation.component.ts, webui/src/app/input-bar/input-bar.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/speakfaster-service.ts, webui/src/utils/text-utils.spec.ts, webui/src/utils/text-utils.ts
E.g., if the "great" in "I'm great, thanks" is replaced with the word option "good", the comma at the end of the original word should be preserved, leading to the new phrase "I'm good, thanks". Previously, the comma was discarded.
=> [WebUI] During word replacement, preserve word-end punctuation

webui/src/app/abbreviation/abbreviation.component.html, webui/src/app/abbreviation/abbreviation.component.spec.ts, webui/src/app/app.component.html, webui/src/app/app.component.spec.ts, webui/src/app/input-bar/input-bar.component.ts, webui/src/app/phrase/phrase.component.html, webui/src/app/phrase/phrase.component.spec.ts, webui/src/app/phrase/phrase.component.ts
Put a consistent green background on the speak buttons in the PhraseComponents.
Also in this PR:
- Increase sample time from 500 to 600 ms.
=> [WebUI] In study mode, emphasize speak button in phrases

Observer/SpeakFasterObserver Decoder/data_manager.py, Observer/SpeakFasterObserver Decoder/file_naming.py, Observer/SpeakFasterObserver Decoder/process_keypresses.py, Observer/SpeakFasterObserver Decoder/process_keypresses_test.py
Add button "Check keypresses". When this button is clicked, the data manager goes over the merged.tsv and curated_postprocessed.tsv files and look for any keypresses that are missing from the latter. It generates a new tsv file
called keypress_checks.tsv and write it to the session folder, followed by GCS upload. Redacted keys are ignored. Sessions
without a merged.tsv or curated_postprocessed.tsv files are ignored.
=> [DataManager] Add checks for missing and extraneous keypresses

Observer/SpeakFasterObserver Decoder/data_manager.py, Observer/SpeakFasterObserver Decoder/process_keypresses.py, Observer/SpeakFasterObserver Decoder/process_keypresses_test.py
1. Ensure that during batch keypress checking, the session prefix passed to the `_check_keypresses()` call contains the full path.
2. Tolerate missing keypresses at the beginning in the logic of `check_keypresses()`. Previously, if the first few keypresses in ref_keypresses are missing from proc_keypresses, an error will be thrown.
=> [DataManager] Fix session prefix logic

webui/src/app/abbreviation/abbreviation.component.html, webui/src/app/abbreviation/abbreviation.component.spec.ts, webui/src/app/abbreviation/abbreviation.component.ts, webui/src/app/settings-ai/settings-ai.component.html, webui/src/app/settings/settings.ts
* Rationale: Prevent unintended entry to the word replacement mode when used with eye gaze.
* This is now tied to the `enableAbbrevExpansionAutoFire` property in the settings. The rationale is that eye gaze users need both this new feature and the existing auto AE trigger feature, whereas mobile (touch) users need neither.
=> [WebUI] When auto AE trigger is on, require 2 clicks for word replacement
